apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloservice
  ports:
    - protocol: TCP
      port: {{ .Values.helloservice.port }}
      targetPort: {{ .Values.helloservice.port }}
  type: ClusterIP