apiVersion: v1
kind: Service
metadata:
  name: profileservice
spec:
  selector:
    app: profileservice
  ports:
    - protocol: TCP
      port: {{ .Values.profileservice.port }}
      targetPort: {{ .Values.profileservice.port }}
  type: ClusterIP